language: erlang
otp_version:
  - 19.0
os:
  - linux
  - osx
env:
  - ARCH=xen CONF=dbg
  - ARCH=xen CONF=opt
  - ARCH=xen CONF=lto
  - ARCH=posix CONF=dbg
  - ARCH=posix CONF=opt
  - ARCH=posix CONF=lto
matrix:
  exclude:
    - os: osx
      env: ARCH=posix CONF=opt
    - os: osx
      env: ARCH=posix CONF=lto
script:
  - travis_wait 60 make -j2 play ARCH=$ARCH CONF=$CONF
sudo: false
